#ifndef CONFIG_GAMMARAY_VERSION_H
#define CONFIG_GAMMARAY_VERSION_H

#define GAMMARAY_VERSION_MAJOR ${GAMMARAY_VERSION_MAJOR}
#define GAMMARAY_VERSION_MINOR ${GAMMARAY_VERSION_MINOR}
#define GAMMARAY_VERSION_PATCH ${GAMMARAY_VERSION_PATCH}
#define GAMMARAY_VERSION_STRING "${GAMMARAY_VERSION_STRING}"
#define GAMMARAY_COMPACT_VERSION_STRING "${GAMMARAY_VERSION_MAJOR}.${GAMMARAY_VERSION_MINOR}.${GAMMARAY_VERSION_PATCH}"

#endif
