#define ENDOSCOPE_VERSION_MAJOR ${ENDOSCOPE_VERSION_MAJOR}
#define ENDOSCOPE_VERSION_MINOR ${ENDOSCOPE_VERSION_MINOR}
#define ENDOSCOPE_VERSION_PATCH ${ENDOSCOPE_VERSION_PATCH}
#define ENDOSCOPE_VERSION_STRING "${ENDOSCOPE_VERSION_STRING}"

