// relative install dirs
#define GAMMARAY_PLUGIN_INSTALL_DIR "${PLUGIN_INSTALL_DIR}"
#define GAMMARAY_LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"
#define GAMMARAY_BIN_INSTALL_DIR "${BIN_INSTALL_DIR}"

#define GAMMARAY_PLUGIN_VERSION "${GAMMARAY_PLUGIN_VERSION}"
#define GAMMARAY_PROBE_ABI "${GAMMARAY_PROBE_ABI}"

// relative inverse install dirs
#define GAMMARAY_INVERSE_BIN_DIR "${GAMMARAY_INVERSE_BIN_DIR}"
#define GAMMARAY_INVERSE_PROBE_DIR "${GAMMARAY_INVERSE_PROBE_DIR}"
#define GAMMARAY_INVERSE_LIBEXEC_DIR "${GAMMARAY_INVERSE_LIBEXEC_DIR}"


// build options
#cmakedefine BUILD_TIMER_PLUGIN

#cmakedefine HAVE_PRIVATE_QT_HEADERS

#cmakedefine HAVE_STDINT_H

#cmakedefine HAVE_QT_WIDGETS
#cmakedefine HAVE_QT_SVG
#cmakedefine HAVE_QT_DESIGNER
#cmakedefine HAVE_QT_PRINTSUPPORT
#cmakedefine HAVE_QT_WEBKIT1

#cmakedefine HAVE_VTK
#cmakedefine HAVE_GRAPHVIZ
